# Generated by Django 3.2 on 2021-04-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('a_type', models.CharField(max_length=255, verbose_name='Тип')),
                ('mod', models.CharField(max_length=255, verbose_name='Модель')),
                ('elect_food', models.CharField(max_length=255, verbose_name='Питание')),
                ('screen_back_type', models.CharField(max_length=255, verbose_name='Тип подсветки экрана')),
                ('screen_diagonal_inch', models.CharField(max_length=255, verbose_name='Диагональ экрана (дюйм)')),
                ('screen_resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('screen_format', models.CharField(max_length=255, verbose_name='Формат экрана')),
                ('screen_refresh_rate', models.CharField(max_length=255, verbose_name='Частота обновления экрана')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('sound_power', models.CharField(max_length=255, verbose_name='Мощность звука')),
                ('maximum_power_consumption', models.CharField(max_length=255, verbose_name='Максимальная потребляемая мощность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Объем батареи')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('sd', models.BooleanField(default=True, verbose_name='Наличие SD карты')),
                ('sd_volume_max', models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем встраивамой памяти')),
                ('namber_of_main_cm', models.CharField(max_length=255, verbose_name='Количество основных камер')),
                ('sim', models.CharField(max_length=255, verbose_name='SIM карта')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Главная камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Цена')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('processor_manufacturer', models.CharField(max_length=255, verbose_name='Производитель процессора')),
                ('processor_ruler', models.CharField(max_length=255, verbose_name='Линейка процессора')),
                ('processor_model', models.CharField(max_length=255, verbose_name='Модель процессора')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Частота процессора')),
                ('ram_type', models.CharField(max_length=255, verbose_name='Тип оперативной памяти')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('video', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Время работы аккумулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
