# Generated by Django 3.2 on 2021-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_auto_20210509_1830'),
        ('shopapp', '0006_auto_20210509_1849'),
    ]

    operations = [
    ]
